package view;

import controller.ControllerView;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import model.Modelo;
import model.Observer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jose
 */
public class View extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form view
     */
    private Modelo model;
    private ControllerView controller;

    public View(Modelo model) {
        initComponents();
        this.model = model;
        this.controller = new ControllerView(model, this);
        this.model.attach(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label_Ordem = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelResult = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelCheckBox = new javax.swing.JPanel();
        boxAdiciona = new javax.swing.JCheckBox();
        boxConverteMinuscula = new javax.swing.JCheckBox();
        boxMaiuscula = new javax.swing.JCheckBox();
        boxTiraVogais = new javax.swing.JCheckBox();
        boxRemoveMaiuscula = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        txtEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pipes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -20, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(560, 70));

        label_Ordem.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Ordem)
                .addContainerGap(544, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_Ordem)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(560, 70));

        labelResult.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelResult)
                .addContainerGap(517, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelResult)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Resultado:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Ordem Escolhida:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 230));

        boxAdiciona.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boxAdiciona.setText("Adiciona A");
        boxAdiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAdicionaActionPerformed(evt);
            }
        });

        boxConverteMinuscula.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boxConverteMinuscula.setText("Converte Minuscula");
        boxConverteMinuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxConverteMinusculaActionPerformed(evt);
            }
        });

        boxMaiuscula.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boxMaiuscula.setText("Converte Maiuscula");
        boxMaiuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMaiusculaActionPerformed(evt);
            }
        });

        boxTiraVogais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boxTiraVogais.setText("Tira vogais");
        boxTiraVogais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTiraVogaisActionPerformed(evt);
            }
        });

        boxRemoveMaiuscula.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boxRemoveMaiuscula.setText("Remove Maiusculas");
        boxRemoveMaiuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRemoveMaiusculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCheckBoxLayout = new javax.swing.GroupLayout(jPanelCheckBox);
        jPanelCheckBox.setLayout(jPanelCheckBoxLayout);
        jPanelCheckBoxLayout.setHorizontalGroup(
            jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckBoxLayout.createSequentialGroup()
                .addGroup(jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckBoxLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(boxAdiciona)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boxRemoveMaiuscula)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckBoxLayout.createSequentialGroup()
                        .addComponent(boxConverteMinuscula)
                        .addGap(18, 18, 18)
                        .addComponent(boxMaiuscula))
                    .addComponent(boxTiraVogais))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelCheckBoxLayout.setVerticalGroup(
            jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxAdiciona)
                    .addComponent(boxConverteMinuscula)
                    .addComponent(boxMaiuscula))
                .addGap(24, 24, 24)
                .addGroup(jPanelCheckBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxRemoveMaiuscula)
                    .addComponent(boxTiraVogais))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 90));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Entrada:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(68, 68, 68))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 570, 80));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.controller.trataBotao(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxAdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAdicionaActionPerformed
        this.controller.TratarBox(evt);


    }//GEN-LAST:event_boxAdicionaActionPerformed

    private void boxConverteMinusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxConverteMinusculaActionPerformed
        this.controller.TratarBox(evt);

    }//GEN-LAST:event_boxConverteMinusculaActionPerformed

    private void boxMaiusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMaiusculaActionPerformed
        // TODO add your handling code here:
        this.controller.TratarBox(evt);

    }//GEN-LAST:event_boxMaiusculaActionPerformed

    private void boxRemoveMaiusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRemoveMaiusculaActionPerformed
        // TODO add your handling code here:
        this.controller.TratarBox(evt);

    }//GEN-LAST:event_boxRemoveMaiusculaActionPerformed

    private void boxTiraVogaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTiraVogaisActionPerformed
        // TODO add your handling code here:
        this.controller.TratarBox(evt);

    }//GEN-LAST:event_boxTiraVogaisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.controller.trataBotao(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxAdiciona;
    private javax.swing.JCheckBox boxConverteMinuscula;
    private javax.swing.JCheckBox boxMaiuscula;
    private javax.swing.JCheckBox boxRemoveMaiuscula;
    private javax.swing.JCheckBox boxTiraVogais;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCheckBox;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel label_Ordem;
    private javax.swing.JTextField txtEntrada;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Update() {
           this.labelResult.setText(model.getResultado());
    }

    public JCheckBox getBoxAdiciona() {
        return boxAdiciona;
    }

    public void setBoxAdiciona(JCheckBox boxAdiciona) {
        this.boxAdiciona = boxAdiciona;
    }

    public JCheckBox getBoxConverteMinuscula() {
        return boxConverteMinuscula;
    }

    public void setBoxConverteMinuscula(JCheckBox boxConverteMinuscula) {
        this.boxConverteMinuscula = boxConverteMinuscula;
    }

    public JCheckBox getBoxMaiuscula() {
        return boxMaiuscula;
    }

    public void setBoxMaiuscula(JCheckBox boxMaiuscula) {
        this.boxMaiuscula = boxMaiuscula;
    }

    public JTextField getTxtEntrada() {
        return txtEntrada;
    }

    public void setTxtEntrada(JTextField txtEntrada) {
        this.txtEntrada = txtEntrada;
    }

    public JCheckBox getBoxRemoveMaiuscula() {
        return boxRemoveMaiuscula;
    }

    public void setBoxRemoveMaiuscula(JCheckBox boxRemoveMaiuscula) {
        this.boxRemoveMaiuscula = boxRemoveMaiuscula;
    }

    public JCheckBox getBoxTiraVogais() {
        return boxTiraVogais;
    }

    public void setBoxTiraVogais(JCheckBox boxTiraVogais) {
        this.boxTiraVogais = boxTiraVogais;
    }

    public JLabel getLabel_Ordem() {
        return label_Ordem;
    }

    public void setLabel_Ordem(JLabel label_Ordem) {
        this.label_Ordem = label_Ordem;
    }
      public JLabel getLabelResult() {
        return labelResult;
    }

    public void setLabelResult(JLabel labelResult) {
        this.labelResult = labelResult;
    }
  
}
